name: Deploy Python Odoo Leads

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REGION: us-east-1
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ODOO_URL: "https://sheltertest.odoo.com"
      ODOO_DB: "sheltertest"
      ODOO_PASSWORD: ${{ secrets.ODOO_PASSWORD }}
      ODOO_USERNAME: ${{ secrets.ODOO_USERNAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: pytest tests/ # optional, if you have tests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: CDK Bootstrap (Idempotent)
        run: npx cdk bootstrap aws://${{ env.AWS_ACCOUNT_ID }}/${{ env.REGION }}

      - name: Deploy CDK Stack
        run: |
          export ODOO_URL=${{ env.ODOO_URL }}
          export ODOO_DB=${{ env.ODOO_DB }}
          export ODOO_USERNAME=${{ env.ODOO_USERNAME }}
          export ODOO_PASSWORD=${{ secrets.ODOO_PASSWORD }}
          npx cdk deploy --require-approval never
